title: Said Alí Oviedo Beltrán
logo: /assets/img/picture_profile2.png
description: Ingeniero Industrial | Analista de datos | Técnico en Microfinanzas

show_downloads: true  # Asegúrate de que este atributo se use en el tema que eliges
# Personalización de diseño
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
include:
- style.css
theme: null
include: ['_includes']

#github:
 # zip_url: http://example.com/download.zip
  #another_url: another value
