title: Said Alí Oviedo Beltrán
logo: /assets/img/picture_profile.png
description: Ingeniero Industrial | Analista de datos | Técnico Microfinanciero

show_downloads: false  # Asegúrate de que este atributo se use en el tema que eliges
# Personalización de diseño
theme: jekyll-theme-minima
